import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import DesktopBanner from "../components/DesktopBanner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Desktop gate — shown only on lg+ (1024px+) */}
        <div className="hidden lg:block">
          <DesktopBanner />
        </div>
        {/* App — shown on mobile and tablet only */}
        <div className="lg:hidden">{children}</div>
      </body>
    </html>
  );
}
